version: '3'

services:
  sqs:
    image: roribio16/alpine-sqs
    ports:
      - 9324:9324
      - 9325:9325
    volumes:
    - type: bind
      source: ./sqs/custom.conf
      target: /opt/elasticmq.conf